### ISSUE TITLE
cant open the add on

### ISSUE THREAD

**Issue by sensensen0101** [Gustaf-C/anki-chinese-support-3#68]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

When loading Chinese Support Redux v0142:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/SenMandarinMindset/Library/Application Support/Anki2/addons21/1128979221/__init__.py", line 23, in <module>
    from . import main
  File "/Users/SenMandarinMindset/Library/Application Support/Anki2/addons21/1128979221/main.py", line 32, in <module>
    from .gui import load_menu, unload_menu
  File "/Users/SenMandarinMindset/Library/Application Support/Anki2/addons21/1128979221/gui.py", line 22, in <module>
    from PyQt5.QtGui import QKeySequence
ModuleNotFoundError: No module named 'PyQt5'

**Comment by sensensen0101** [comment]
<img width="551" alt="Screenshot 2024-03-01 at 3 44 03 PM" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/161812426/010953c3-abc4-498d-bd5b-8fef166f996e">
no updates available

**Comment by Gustaf-C** [comment]
That is not my addon, please use https://ankiweb.net/shared/info/1752008591 instead
