### ISSUE TITLE
Debug error with Bulk Fill

### ISSUE THREAD

**Issue by zarlivia** [Gustaf-C/anki-chinese-support-3#83]
Im trying to Bulkfill fields 'All' and whenever I do I get this error.
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\zarao\AppData\Roaming\Anki2\addons21\1752008591\fill.py", line 98, in bulk_fill_all
    'hanzi': get_hanzi(dict(note)),
  File "C:\Users\zarao\AppData\Roaming\Anki2\addons21\1752008591\hanzi.py", line 52, in get_hanzi
    return cleanup(get_first(config['fields']['hanzi'], note))
  File "C:\Users\zarao\AppData\Roaming\Anki2\addons21\1752008591\util.py", line 70, in cleanup
    raise ValueError(text)
ValueError: None

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-06-18T03:37, 'None', mod]
Chinese Support 3 ['1752008591', 2024-02-25T09:37, 'None', mod]
Migaku Anki Add-on ['1846879528', 2024-07-25T11:00, 'None', mod]
Sentence adder for any language with batch add option ['1682655437', 2024-06-25T16:53, 'None', '']

===IDs of active AnkiWeb add-ons===
1682655437 1752008591 1846879528 2055492159

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

Apologies if im being stupid, this is an amazing add-on... im just really good at accidentally breaking things :(

**Comment by BorisNA** [comment]
This happens when the deck has cards without a "hanzi" field (that is, the deck has cards with another notetype, without "hanzi", for example the "Basic" notetype or like)
