### ISSUE TITLE
Chinese Support 3 Auto Populate Not Working

### ISSUE THREAD

**Issue by smiling-panda-888** [Gustaf-C/anki-chinese-support-3#84]
**Describe the bug**
Anki encounters a problem when I enter in the Hanzi and then press ' Tab' to auto-populate. Occassionally, this is resolved by restarting Anki, however the issue always comes back.

(Debug info below)
--------------------------------------------------------------------------------------------------------------
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 160, in _onCmd
  File "aqt.webview", line 695, in _onBridgeCmd
  File "aqt.editor", line 425, in onBridgeCmd
  File "_aqt.hooks", line 2548, in __call__
  File "anki.hooks", line 45, in runFilter
  File "C:\Users\esemo\AppData\Roaming\Anki2\addons21\1752008591\edit.py", line 121, in onFocusLost
    if not update_fields(note, field, allFields):
  File "C:\Users\esemo\AppData\Roaming\Anki2\addons21\1752008591\behavior.py", line 352, in update_fields
    fill_sound(hanzi, copy)
  File "C:\Users\esemo\AppData\Roaming\Anki2\addons21\1752008591\behavior.py", line 246, in fill_sound
    s = sound(hanzi, config['speech'])
  File "C:\Users\esemo\AppData\Roaming\Anki2\addons21\1752008591\sound.py", line 51, in sound
    return '[sound:%s]' % AudioDownloader(hanzi, source).download()
  File "C:\Users\esemo\AppData\Roaming\Anki2\addons21\1752008591\tts.py", line 52, in download
    self.func()
  File "C:\Users\esemo\AppData\Roaming\Anki2\addons21\1752008591\tts.py", line 59, in get_google
    tts.save(self.path)
  File "C:\Users\esemo\AppData\Roaming\Anki2\addons21\1752008591\lib\gtts\tts.py", line 312, in save
    with open(str(savefile), 'wb') as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\esemo\\AppData\\Roaming\\Anki2\\User 1\\collection.media\\我觉得厅和说还可以，\n读和写不好， 很多字我都不知道是什么意思_google_zh-CN.mp3'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Chinese Support 3 ['1752008591', 2024-02-25T10:37, 'None', mod]

===IDs of active AnkiWeb add-ons===
1752008591

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

----------------------------------------------------------------------------------------------------------------------------------------

**Expected behavior**

**Screenshots**
![Anki_ChineseSupport_Error](https://github.com/user-attachments/assets/8082f807-c08b-4464-8808-5aa5b0637492)

**Specs (please complete the following information):**
 - OS:  Windows
 - Anki Version 24.06.3 (d678e393)⁩
- Chinese Support 3 v0.17.1

The auto populate used to work for me, but has recently given me issues for some reason.

**Comment by kieranlblack** [comment]
Hi, could you send the raw html from the Hanzi field? It looks like a `\` is being inserted for a newline character. Is it multiline?

**Comment by smiling-panda-888** [comment]
<div>我觉得厅和说还可以， 读和写不好，
很多字我都不知道是什么意思。</div>

![Hanzi HTLM](https://github.com/user-attachments/assets/baabac24-6c3f-4fa3-a816-fe95780bc56c)

Is this what you are looking for?

**Comment by kieranlblack** [comment]
Yup that's it. The newline in the field after the comma is messing with the plugin since it doesn't totally sanitize this input for a path. For the time being you can work around this by not using newlines, try using a `<br />` instead or just remove the line break entirely.

ps from one Chinese learner to another you might want to check that 厅 is the right character there 😉

**Comment by smiling-panda-888** [comment]
> Yup that's it. The newline in the field after the comma is messing with the plugin since it doesn't totally sanitize this input for a path. For the time being you can work around this by not using newlines, try using a `<br />` instead or just remove the line break entirely.
> 
> ps from one Chinese learner to another you might want to check that 厅 is the right character there 😉

Thanks man this solved the issue. Super helpful!
