### ISSUE TITLE
Error when auto-populating (No AWS credentials provided)

### ISSUE THREAD

**Issue by SashaDef** [Gustaf-C/anki-chinese-support-3#93]
When using tab to auto-populate the cards, I get an error saying that aws credentials have not been provided.

After getting this error, tab no longer works to auto-populate.

### Steps to reproduce the behavior:
1. Create a new card using the Chinese (Basic) card type.
2. Write in the Hanzi (in my case 医生).
3. Press Tab
4. Error appears.
5. no longer able to use auto-populate

### Specs
 - OS: Windows-10-10.0.22631
 - Anki Version 24.11 
- Chinese Support Version 3 v.0.17.1

### Paste Bin
Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.webview", line 53, in cmd
  File "aqt.webview", line 169, in _onCmd
  File "aqt.webview", line 725, in _onBridgeCmd
  File "aqt.editor", line 418, in onBridgeCmd
  File "_aqt.hooks", line 2548, in __call__
  File "anki.hooks", line 48, in runFilter
  File "C:\Users\valte\AppData\Roaming\Anki2\addons21\1752008591\edit.py", line 121, in onFocusLost
    if not update_fields(note, field, allFields):
  File "C:\Users\valte\AppData\Roaming\Anki2\addons21\1752008591\behavior.py", line 352, in update_fields
    fill_sound(hanzi, copy)
  File "C:\Users\valte\AppData\Roaming\Anki2\addons21\1752008591\behavior.py", line 246, in fill_sound
    s = sound(hanzi, config['speech'])
  File "C:\Users\valte\AppData\Roaming\Anki2\addons21\1752008591\sound.py", line 51, in sound
    return '[sound:%s]' % AudioDownloader(hanzi, source).download()
  File "C:\Users\valte\AppData\Roaming\Anki2\addons21\1752008591\tts.py", line 52, in download
    self.func()
  File "C:\Users\valte\AppData\Roaming\Anki2\addons21\1752008591\tts.py", line 101, in get_aws
    response = requests.post(url, json=query, auth=signer)
  File "requests.api", line 115, in post
  File "requests.api", line 59, in request
  File "requests.sessions", line 575, in request
  File "requests.sessions", line 484, in prepare_request
  File "requests.models", line 371, in prepare
  File "requests.models", line 602, in prepare_auth
  File "C:\Users\valte\AppData\Roaming\Anki2\addons21\1752008591\aws.py", line 155, in __call__
    raise ValueError('No AWS credentials given')
ValueError: No AWS credentials given

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-11-06T18:34, 'None', '']
Chinese Support 3 ['1752008591', 2024-02-25T02:37, 'None', mod]
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T19:19, 'None', '']
Hanzi Stats ['181243826', 2023-12-03T15:34, 'None', '']
ImageResizer ['1214357311', 2023-12-02T18:58, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T19:43, 'None', '']
VocabAi  Baserow Import ['1327473241', 2024-03-16T16:13, 'None', '']

===IDs of active AnkiWeb add-ons===
1210908941 1214357311 1327473241 1752008591 1771074083 181243826 2055492159

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by kieranlblack** [comment]
Hi, it seems like you are using the Amazon Polly speech engine. If you don't have credentials for this then please use a different one.
![image](https://github.com/user-attachments/assets/f8b3064a-b2f3-4b7a-b4e3-d8579475a768)
